### ISSUE TITLE
setup to be consumed via plop.load

### ISSUE THREAD

**Issue by amwmedia** [alsiola/plop-prettier#1]
Hey, nice work on this! Have you see that plop supports the ability to setup reusable packages that can be easily loaded into another plopfile via [plop.load()](https://github.com/amwmedia/plop/blob/master/plop-load.md)? I'd be happy to help get this in place if you'd like. :-)

**Comment by alsiola** [comment]
Hi - I wasn't aware of `load` but it looks like something that would be very worthwhile to support.  If I understand correctly then we would just need to add a default include, something like:

````
plop.setDefaultInclude({ actionTypes: true });
````

Then the prettier package could be added with:
````
plop.load("plop-prettier");
````

Or am I missing something here?

**Comment by alsiola** [comment]
Could you run a quick eye over #2 ? Would be much appreciated.

**Comment by crutchcorn** [comment]
This is a _very_ late notice of this project on my radar, but would you be interested in adding this project to the `awesome-plop` repo?

https://github.com/plopjs/awesome-plop

Love the project!
