### ISSUE TITLE
Take .prettierrc into consideration

### ISSUE THREAD

**Issue by manuelbieh** [alsiola/plop-prettier#3]
Currently when I load plop-prettier it looks like the added file is formatted using the default prettier options. I know I can pass a prettier config as second parameter to `plop.load()` but I think `plop-prettier` should automatically respect an existing `.prettierrc` in the project folder.

**Comment by alsiola** [comment]
Hi @manuelbieh, I missed this issue entirely. Agree with your point regarding `.prettierrc` files, we should respect the different places that config may appear (package.json, prettierrc etc.) and use the same order of precedence as the prettier CLI. I'll look into this soon.
